# Generated by Django 3.1.2 on 2020-10-21 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0002_customer_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topping',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Vegan-friendly'), (1, 'Vegetarian-friendly'), (2, 'Non-vegan non-veg')], default=2),
            preserve_default=False,
        ),
    ]
